### ISSUE TITLE
error in query with comment

### ISSUE THREAD

**Issue by fpvandoorn** [leanprover-community/LeanSearchClient#11]
In the second and third command we get the message `Could not contact Loogle server`, while the first and last commands work
```lean
import Mathlib.Tactic.Common

#loogle ?a * _ < ?a * _ ↔ _
#loogle ?a * _ < ?a * _ ↔ _ /- foo -/
#loogle ?a * _ < ?a * _ ↔ _


-- comment
#loogle ?a * _ < ?a * _ ↔ _
```

**Comment by siddhartha-gadgil** [comment]
The problem was that `/-` was not escaped and so became part of a nonsensical url. Also while parsing `\n` was introduced. 
Pushed a crude fix splitting on `/-` and replacing newlines by spaces.

**Comment by siddhartha-gadgil** [comment]
Seems that the quickfix works. Closing this. Please reopen if the issue reappears.
